--- #YAML:1.0
name:               Test-OpenLDAP
version:            0.04
abstract:           Creates a temporary instance of OpenLDAP's slapd daemon to run tests against.
author:
    - David Dick <ddick@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config:       0
    Data::UUID:   0
    DirHandle:    0
    English:      0
    File::Temp:   0
    FileHandle:   0
    Net::LDAP:    0
    POSIX:        0
    Test::More:   0
    URI::Escape:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
