--- #YAML:1.0
name:               Test-OpenLDAP
version:            0.01
abstract:           Creates a temporary instance of OpenLDAP's slapd daemon to run tests against.
author:
    - David Dick <ddick@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
